name: .NET

on:
  push:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore #/p:ContinuousIntegrationBuild=true
    - name: Test
      run: dotnet test --no-restore --verbosity normal --logger trx --results-directory "TestResults" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
    - name: Publish Test
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Test Results on dev
        path: ./TestResults/*.trx
        reporter: dotnet-trx
    - name: Create an Issue
      if: failure()
      uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: .github/ultimate_issue_template.md 
    - uses: codecov/codecov-action@v2
      with:
        #files: ./coverage1.xml,./coverage2.xml # optional
        flags: unittests # optional
        name: codecov-umbrella # optional
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        tag: 1.1.${{github.run_number}}
        body: New Release
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: "./UltimateApp/bin/Release/netcoreapp3.0/UltimateApp" 
