name: .NET

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        tag: 1.1.${{github.run_number}}
        body: New Release
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: "./UltimateApp/bin/Release/netcoreapp3.1/UltimateApp" 
